# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Board.create(name: 'mu', full_name: 'Music', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et laoreet nunc. In feugiat metus tortor, sit amet tempus nisi volutpat non. Duis diam magna, fringilla a cursus vitae, eleifend et sapien. Curabitur id libero lorem. Integer et ipsum laoreet.')
Board.create(name: 'nu', full_name: 'Nuan', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et laoreet nunc. In feugiat metus tortor, sit amet tempus nisi volutpat non. Duis diam magna, fringilla a cursus vitae, eleifend et sapien. Curabitur id libero lorem. Integer et ipsum laoreet.')
Board.create(name: 'v', full_name: 'Video', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et laoreet nunc. In feugiat metus tortor, sit amet tempus nisi volutpat non. Duis diam magna, fringilla a cursus vitae, eleifend et sapien. Curabitur id libero lorem. Integer et ipsum laoreet.')
Board.create(name: 't', full_name: 'Technology', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et laoreet nunc. In feugiat metus tortor, sit amet tempus nisi volutpat non. Duis diam magna, fringilla a cursus vitae, eleifend et sapien. Curabitur id libero lorem. Integer et ipsum laoreet.')
Board.create(name: 'f', full_name: 'Food', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et laoreet nunc. In feugiat metus tortor, sit amet tempus nisi volutpat non. Duis diam magna, fringilla a cursus vitae, eleifend et sapien. Curabitur id libero lorem. Integer et ipsum laoreet.')
Board.create(name: 'bus', full_name: 'Business', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et laoreet nunc. In feugiat metus tortor, sit amet tempus nisi volutpat non. Duis diam magna, fringilla a cursus vitae, eleifend et sapien. Curabitur id libero lorem. Integer et ipsum laoreet.')
Board.create(name: 's', full_name: 'Sport', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et laoreet nunc. In feugiat metus tortor, sit amet tempus nisi volutpat non. Duis diam magna, fringilla a cursus vitae, eleifend et sapien. Curabitur id libero lorem. Integer et ipsum laoreet.')
Board.create(name: 'au', full_name: 'Autos', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et laoreet nunc. In feugiat metus tortor, sit amet tempus nisi volutpat non. Duis diam magna, fringilla a cursus vitae, eleifend et sapien. Curabitur id libero lorem. Integer et ipsum laoreet.')
Board.create(name: 'hse', full_name: 'Higher School of Economics ', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et laoreet nunc. In feugiat metus tortor, sit amet tempus nisi volutpat non. Duis diam magna, fringilla a cursus vitae, eleifend et sapien. Curabitur id libero lorem. Integer et ipsum laoreet.')